name: 'coverage'

on:
    push:
        branches:
            - master
            - main

    pull_request_target:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                output: report-markdown
